// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBHWcOCzpl9rlJhg2Xqc6JGLiqxqNDevQ',
    appId: '1:208994878518:web:10f37dadf664c100cf4497',
    messagingSenderId: '208994878518',
    projectId: 'cgcfluttertraining',
    authDomain: 'cgcfluttertraining.firebaseapp.com',
    storageBucket: 'cgcfluttertraining.firebasestorage.app',
    measurementId: 'G-D5YHGGFQ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNv8CsI1F901JIwfwCXf2ivulb8bJVNU',
    appId: '1:208994878518:android:972121376a8dad7fcf4497',
    messagingSenderId: '208994878518',
    projectId: 'cgcfluttertraining',
    storageBucket: 'cgcfluttertraining.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMUOLur10HfiVO3xiiOFlmHUItJODUoG4',
    appId: '1:208994878518:ios:1eb3d2fc96eb1d1dcf4497',
    messagingSenderId: '208994878518',
    projectId: 'cgcfluttertraining',
    storageBucket: 'cgcfluttertraining.firebasestorage.app',
    iosBundleId: 'com.example.cgcflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMUOLur10HfiVO3xiiOFlmHUItJODUoG4',
    appId: '1:208994878518:ios:1eb3d2fc96eb1d1dcf4497',
    messagingSenderId: '208994878518',
    projectId: 'cgcfluttertraining',
    storageBucket: 'cgcfluttertraining.firebasestorage.app',
    iosBundleId: 'com.example.cgcflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBHWcOCzpl9rlJhg2Xqc6JGLiqxqNDevQ',
    appId: '1:208994878518:web:ad3dea0a16860832cf4497',
    messagingSenderId: '208994878518',
    projectId: 'cgcfluttertraining',
    authDomain: 'cgcfluttertraining.firebaseapp.com',
    storageBucket: 'cgcfluttertraining.firebasestorage.app',
    measurementId: 'G-0GV325P4BG',
  );
}
